### ISSUE TITLE
[Flutter Android] The webview still login after call Logout()

### ISSUE THREAD

**Issue by jamestsang** [authgear/authgear-sdk-flutter#64]
I got a problem, the webview keep login status after call logout function 

Steps:
1, Call authenticate() then open the webview
2, Login Azure AD B2C with username password
3, Call logout()
4, Call authenticate() again, it will login previous account automatically.

Flutter (Channel stable, 3.16.4)
flutter_authgear 1.6.0

**Comment by fungc-io** [comment]
Hi @jamestsang , in step 4, do you still see the AuthUI for you to select the "Login with Azure AD B2C" button? Or do you see a "Continue with this account" screen?

**Comment by fungc-io** [comment]
Hi @jamestsang , 
In step 4, I understand that Azure AD B2C automatically logs in to the same account without requiring a username and password.

It is because `customTabs` on the Android device stored the session of AD B2C after login and it remains after logout in Authgear. Our SDK uses `customTabs` to open the login page by default.

One workaround is to use a custom webkit webview UI Implementation for opening the login page. You can find the [example here](https://docs.authgear.com/how-to-guide/mobile-apps/using-webview-to-open-the-authgear-ui#id-3.-implement-custom-uiimplementation) and [documentation here](https://authgear.github.io/authgear-sdk-flutter/authgear/UIImplementation-class.html). And clear the cookies in your custom webkit webview UI Implementation when the user login, so it starts new. Please note that "Login with Google" and "Passkey" are not supported in Webkit Webview.

For cases when `customTabs` is preferred, I'm discussing with our team to see if a workaround is possible, we will update here.

**Comment by fungc-io** [comment]
Hi @jamestsang ,
In step 4, I understand that Azure AD B2C automatically logs in to the same account without requiring a username and password.

It is because `customTabs` on the Android device stored the session of AD B2C after login and it remains after logout in Authgear.

By setting `prompt: "login"` in the authenticate method during login, Authgear will forward the prompt to the Azure AD B2C connection. Which should force it to ask for a username and password again. 
You can refer to: https://authgear.github.io/authgear-sdk-flutter/authgear/Authgear/authenticate.html

**Comment by jamestsang** [comment]
Hi,

Thank you for your prompt reply.
It solved my problem.

**Comment by fungc-io** [comment]
@jamestsang 
Awesome! We're thrilled to have resolved your issue.
Thank you for choosing Authgear.
